import type { Metadata } from 'next';
export const metadata: Metadata = { title:'AGI Counsel Network｜智能时代的法律判断力', description:'连接人工智能生态各环节法律专业人士的可信同行网络。', alternates:{canonical:'/zh/',languages:{en:'/','zh-CN':'/zh/'}} };
const layers=[['01','能源','为智能提供动力'],['02','芯片','支撑规模化算力'],['03','基础设施','建设智能时代底座'],['04','模型','推动能力边界'],['05','应用','改变工作与生活']];
const work=[['01','深度对话','围绕塑造 AI 生态的法律议题，开展坦诚且非公开的同行交流。'],['02','基准与实践分享','交流新兴标准、运营模式以及 AI 法律工作的真实实践。'],['03','小型聚会','以邀请制的小规模交流，追求深度而非人数。'],['04','AI 法律人的未来','共同探索人工智能如何改变法律判断、制度与我们的职业。']];
const principles=[['信任','为同行之间的坦诚交流创造安全环境。'],['实践交流','重视真实经验与可用洞见，而非空泛讨论。'],['拒绝商业推销','这里是学习与交流的空间，而非获客渠道。'],['以个人身份参与','成员以个人身份交流，不代表所在机构背书。']];
export default function ChineseHome(){return <main lang="zh-CN">
<header className="site-header"><a className="brand" href="#top"><span className="brand-mark">A</span><span>AGI Counsel Network</span></a><nav aria-label="主导航"><a href="#about">关于我们</a><a href="#work">我们做什么</a><a href="#principles">社群原则</a><a className="language-switch" href="/">EN</a><a className="nav-join" href="#join">加入网络</a></nav></header>
<section className="hero" id="top"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="eyebrow"><span/> 独立同行社群</div><h1>智能时代的<br/>法律判断力。</h1><p className="hero-copy">连接人工智能生态各环节法律专业人士的可信同行网络。</p><div className="hero-actions"><a className="button button-light" href="#join">加入网络 <span>↗</span></a><a className="text-link" href="#about">了解我们的使命 <span>↓</span></a></div><div className="hero-footer"><span>跨越专业边界</span><span>贯穿 AI 全产业链</span><span>以信任为基础</span></div></section>
<section className="intro section" id="about"><div className="section-label">01 / 我们为何存在</div><div className="intro-content"><p className="kicker">法律工作正在改变。</p><h2>人工智能不仅在重塑法律与商业，也在重新定义法律专业人士的角色。</h2><div className="intro-columns"><p>许多最重要的问题并没有现成答案。它们跨越行业、技术、司法辖区与组织边界，不断涌现。</p><p>AGI Counsel Network 汇聚资深法律专业人士，交流实践、磨砺判断，并共同面对未来。</p></div></div></section>
<section className="stack-section"><div className="section stack-heading"><div className="section-label">02 / 贯穿 AI 产业链</div><div><p className="kicker">同一生态，共同议题。</p><h2>连接人工智能每一层的法律专业人士。</h2></div></div><div className="layer-cake">{layers.map(([n,t,b])=><div className="layer" key={t}><span>{n}</span><strong>{t}</strong><small>{b}</small></div>)}</div></section>
<section className="section work" id="work"><div className="section-label">03 / 我们做什么</div><div className="work-content"><p className="kicker">追求深度，远离喧嚣。</p><h2>为那些难以在大会舞台上充分展开的对话，创造空间。</h2><div className="work-grid">{work.map(([n,t,b])=><article key={t}><span>{n}</span><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>
<section className="principles" id="principles"><div className="section principles-inner"><div className="section-label section-label-gold">04 / 社群原则</div><div className="principles-content"><p className="kicker kicker-gold">我们如何参与。</p><h2>严肃的同行社群，始于清晰的共同约定。</h2><div className="principles-list">{principles.map(([t,b],i)=><div className="principle" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{b}</p></div>)}</div></div></div></section>
<section className="join section" id="join"><div className="join-card"><p className="kicker kicker-light">一个有意保持精简的网络。</p><h2>带来你的判断。<br/>带走更好的问题。</h2><p>会员目前实行邀请制。如果你认同我们的使命，欢迎与我们联系。</p><a className="button button-light" href="mailto:hello@agicounsel.org?subject=AGI%20Counsel%20Network%20—%20加入意向">表达加入意向 <span>↗</span></a></div></section>
<footer><a className="brand" href="#top"><span className="brand-mark">A</span><span>AGI Counsel Network</span></a><p>连接人工智能生态各环节法律专业人士的独立同行社群。</p><div><a href="mailto:hello@agicounsel.org">hello@agicounsel.org</a><span>© 2026 AGI Counsel Network</span></div></footer>
</main>}
